export const defaultSchema = [
  {
    code: "switch",
    id: 1,
    mode: "rw",
    name: "开关",
    property: { type: "bool" },
    type: "obj",
  },
  {
    code: "milk",
    id: 101,
    mode: "rw",
    name: "start_milk",
    property: { type: "bool" },
    type: "obj",
  },
  {
    code: "water",
    id: 102,
    mode: "rw",
    name: "start_water",
    property: { type: "bool" },
    type: "obj",
  },
  {
    code: "clean",
    id: 103,
    mode: "rw",
    name: "start_clean",
    property: { type: "bool" },
    type: "obj",
  },
  {
    code: "powder",
    id: 104,
    mode: "rw",
    name: "start_powder",
    property: { type: "bool" },
    type: "obj",
  },
  {
    code: "work_mode",
    id: 105,
    mode: "rw",
    name: "work_mode",
    property: {
      type: "enum",
      range: ["milk", "water", "powder", "clean", "idle"],
    },
    type: "obj",
  },
  {
    code: "working_status",
    id: 122,
    mode: "ro",
    name: "working_status",
    property: { type: "bool" },
    type: "obj",
  },
  {
    code: "temp",
    id: 106,
    mode: "rw",
    name: "temp_set",
    property: { type: "enum", range: ["37", "40", "45", "70"] },
    type: "obj",
  },
  {
    code: "ml",
    id: 107,
    mode: "rw",
    name: "volume_set_ml",
    property: {
      type: "value",
      min: 60,
      max: 300,
      step: 10,
      scale: 0,
      unit: "mL",
    },
    type: "obj",
  },
  {
    code: "oz",
    id: 108,
    mode: "rw",
    name: "volume_set_oz",
    property: {
      type: "value",
      min: 2,
      max: 10,
      step: 1,
      scale: 0,
      unit: "oz",
    },
    type: "obj",
  },
  {
    code: "unit_set",
    id: 109,
    mode: "rw",
    name: "unit_set",
    property: { type: "enum", range: ["mL", "oz"] },
    type: "obj",
  },
  {
    code: "formula_ratio",
    id: 110,
    mode: "rw",
    name: "formula_ratio",
    property: {
      type: "value",
      min: 36,
      max: 660,
      step: 1,
      scale: 1,
      unit: "g",
    },
    type: "obj",
  },
  {
    code: "powder_density",
    id: 111,
    mode: "ro",
    name: "powder_density",
    property: {
      type: "value",
      min: 6,
      max: 15,
      step: 1,
      scale: 0,
    },
    type: "obj",
  },
  {
    code: "start_block_reason",
    id: 112,
    mode: "ro",
    name: "start_block_reason",
    property: {
      type: "enum",
      range: [
        "none",
        "water_tank_missing",
        "low_water",
        "powder_box_missing",
        "funnel_missing",
        "bottle_missing",
        "hot_alert",
      ],
    },
    type: "obj",
  },
  {
    code: "scene_feed_request",
    id: 113,
    mode: "ro",
    name: "scene_feed_request",
    property: { type: "enum", range: ["none", "hungry_pending"] },
    type: "obj",
  },
  {
    code: "remind_funnel_clean",
    id: 114,
    mode: "ro",
    name: "remind_funnel_clean",
    property: { type: "bool" },
    type: "obj",
  },
  {
    code: "remind_daily_powder_clean",
    id: 115,
    mode: "ro",
    name: "remind_daily_powder_clean",
    property: { type: "bool" },
    type: "obj",
  },
  {
    code: "remind_tank_clean",
    id: 116,
    mode: "ro",
    name: "remind_tank_clean",
    property: { type: "bool" },
    type: "obj",
  },
  {
    code: "wifi_status",
    id: 119,
    mode: "ro",
    name: "wifi_status",
    property: { type: "enum", range: ["offline", "connecting", "online"] },
    type: "obj",
  },
  {
    code: "drink_record_upload",
    id: 120,
    mode: "ro",
    name: "drink_record_upload",
    property: { type: "raw" },
    type: "obj",
  },
  {
    code: "cancel_work",
    id: 121,
    mode: "rw",
    name: "cancel_work",
    property: { type: "bool" },
    type: "obj",
  },
  {
    code: "error_code",
    id: 123,
    mode: "ro",
    name: "error_code",
    property: {
      type: "enum",
      range: ["none", "Hot", "E01", "E02", "C01", "C02"],
    },
    type: "obj",
  },
] as const;

export type SchemaCode = (typeof defaultSchema)[number]["code"];
