export const defaultSchema = [
  {
    attr: 0,
    canTrigger: true,
    code: "temp_current",
    defaultRecommend: true,
    editPermission: true,
    executable: false,
    extContent: "",
    iconname: "icon-temp",
    id: 107,
    mode: "ro",
    name: "当前温度",
    property: {
      unit: "℃",
      min: 0,
      max: 1000,
      scale: 0,
      step: 1,
      type: "value",
    },
    type: "obj",
  },
  {
    attr: 0,
    canTrigger: true,
    code: "humidity_value",
    defaultRecommend: true,
    editPermission: true,
    executable: false,
    extContent: "",
    iconname: "icon-humidity",
    id: 108,
    mode: "ro",
    name: "当前湿度",
    property: {
      unit: "%",
      min: 0,
      max: 1000,
      scale: 0,
      step: 1,
      type: "value",
    },
    type: "obj",
  },
  {
    attr: 0,
    canTrigger: true,
    code: "fan",
    defaultRecommend: true,
    editPermission: true,
    executable: true,
    extContent: "",
    iconname: "icon-fan",
    id: 101,
    mode: "rw",
    name: "风扇",
    property: {
      unit: "",
      min: 0,
      max: 5,
      scale: 0,
      step: 1,
      type: "value",
    },
    type: "obj",
  },
  {
    attr: 0,
    canTrigger: true,
    code: "mist",
    defaultRecommend: true,
    editPermission: true,
    executable: true,
    extContent: "",
    iconname: "icon-mist",
    id: 102,
    mode: "rw",
    name: "水雾",
    property: {
      unit: "",
      min: 0,
      max: 2,
      scale: 0,
      step: 1,
      type: "value",
    },
    type: "obj",
  },
  {
    attr: 0,
    canTrigger: true,
    code: "cooling",
    defaultRecommend: true,
    editPermission: true,
    executable: true,
    extContent: "",
    iconname: "icon-cooling",
    id: 103,
    mode: "rw",
    name: "制冷",
    property: {
      unit: "",
      min: 0,
      max: 2,
      scale: 0,
      step: 1,
      type: "value",
    },
    type: "obj",
  },
  {
    attr: 0,
    canTrigger: true,
    code: "light",
    defaultRecommend: true,
    editPermission: true,
    executable: true,
    extContent: "",
    iconname: "icon-light",
    id: 104,
    mode: "rw",
    name: "灯光",
    property: {
      unit: "",
      min: 0,
      max: 16777215,
      scale: 0,
      step: 1,
      type: "value",
    },
    type: "obj",
  },
  {
    attr: 0,
    canTrigger: true,
    code: "pir",
    defaultRecommend: true,
    editPermission: true,
    executable: false,
    extContent: "",
    iconname: "icon-pir",
    id: 105,
    mode: "ro",
    name: "红外感应",
    property: {
      type: "bool",
    },
    type: "obj",
  },
  {
    attr: 0,
    canTrigger: true,
    code: "o3",
    defaultRecommend: true,
    editPermission: true,
    executable: true,
    extContent: "",
    iconname: "icon-o3",
    id: 106,
    mode: "rw",
    name: "臭氧",
    property: {
      unit: "",
      min: 0,
      max: 7,
      scale: 0,
      step: 1,
      type: "value",
    },
    type: "obj",
  },
  {
    attr: 0,
    canTrigger: true,
    code: "power_switch",
    defaultRecommend: true,
    editPermission: true,
    executable: true,
    extContent: "",
    iconname: "icon-power",
    id: 110,
    mode: "rw",
    name: "电源",
    property: {
      type: "bool",
    },
    type: "obj",
  },
] as const;
