export const defaultSchema = [
  {
    code: "switch",
    id: 1,
    mode: "rw",
    name: "switch",
    property: { type: "bool" },
    type: "obj",
  },
  {
    code: "work_mode",
    id: 101,
    mode: "rw",
    name: "work_mode",
    property: { type: "enum", range: ["milk", "water", "powder", "clean"] },
    type: "obj",
  },
  {
    code: "working_status",
    id: 102,
    mode: "rw",
    name: "working_status",
    property: { type: "bool" },
    type: "obj",
  },
  {
    code: "milkbox_sensor",
    id: 103,
    mode: "ro",
    name: "milkbox_sensor",
    property: { type: "bool" },
    type: "obj",
  },
  {
    code: "funnel_sensor",
    id: 104,
    mode: "ro",
    name: "funnel_sensor",
    property: { type: "bool" },
    type: "obj",
  },
  {
    code: "bottle_sensor",
    id: 105,
    mode: "ro",
    name: "bottle_sensor",
    property: { type: "bool" },
    type: "obj",
  },
  {
    code: "watertank_sensor",
    id: 106,
    mode: "ro",
    name: "watertank_sensor",
    property: { type: "bool" },
    type: "obj",
  },
  {
    code: "temp",
    id: 107,
    mode: "rw",
    name: "temp",
    property: { type: "value", min: 20, max: 40, step: 5, scale: 0, unit: "C" },
    type: "obj",
  },
  {
    code: "unit_set",
    id: 108,
    mode: "rw",
    name: "unit_set",
    property: { type: "enum", range: ["mL", "oz"] },
    type: "obj",
  },
  {
    code: "ml",
    id: 109,
    mode: "rw",
    name: "ml",
    property: {
      type: "value",
      min: 60,
      max: 300,
      step: 10,
      scale: 0,
      unit: "mL",
    },
    type: "obj",
  },
  {
    code: "oz",
    id: 110,
    mode: "rw",
    name: "oz",
    property: { type: "value", min: 2, max: 10, step: 1, scale: 0, unit: "oz" },
    type: "obj",
  },
  {
    code: "formula_water",
    id: 111,
    mode: "rw",
    name: "formula_water",
    property: {
      type: "value",
      min: 10,
      max: 300,
      step: 1,
      scale: 0,
      unit: "mL",
    },
    type: "obj",
  },
  {
    code: "formula_ratio",
    id: 112,
    mode: "rw",
    name: "formula_ratio",
    property: {
      type: "value",
      min: 25,
      max: 350,
      step: 1,
      scale: 1,
      unit: "g",
    },
    type: "obj",
  },
  {
    code: "formula_density",
    id: 113,
    mode: "rw",
    name: "formula_density",
    property: { type: "value", min: 5, max: 15, step: 1, scale: 1 },
    type: "obj",
  },
  {
    code: "remind_funnel_clean",
    id: 114,
    mode: "ro",
    name: "remind_funnel_clean",
    property: { type: "bool" },
    type: "obj",
  },
  {
    code: "drink_record_upload",
    id: 115,
    mode: "ro",
    name: "drink_record_upload",
    property: { type: "raw" },
    type: "obj",
  },
  {
    code: "error_code",
    id: 116,
    mode: "ro",
    name: "error_code",
    property: { type: "enum", range: ["none"] },
    type: "obj",
  },
  {
    code: "scene_feed_request",
    id: 117,
    mode: "rw",
    name: "scene_feed_request",
    property: { type: "enum", range: ["none", "hungry_pending"] },
    type: "obj",
  },
  {
    code: "child_lock",
    id: 118,
    mode: "rw",
    name: "child_lock",
    property: { type: "bool" },
    type: "obj",
  },
  {
    code: "feeding_record_context",
    id: 119,
    mode: "rw",
    name: "Feeding Record Context",
    property: { type: "string", maxlen: 512 },
    type: "obj",
  },
] as const;

export type SchemaCode = (typeof defaultSchema)[number]["code"];
