export default {
  switch: "switch",
  workMode: "work_mode",
  workingStatus: "working_status",
  milkboxSensor: "milkbox_sensor",
  funnelSensor: "funnel_sensor",
  bottleSensor: "bottle_sensor",
  watertankSensor: "watertank_sensor",
  tempSet: "temp",
  volumeMl: "ml",
  volumeOz: "oz",
  unitSet: "unit_set",
  formulaWater: "formula_water",
  formulaRatio: "formula_ratio",
  formulaDensity: "formula_density",
  sceneFeedRequest: "scene_feed_request",
  remindFunnelClean: "remind_funnel_clean",
  feedingContext: "feeding_record_context",
  feedingRecordConfirmation: "feeding_record_confir",
  drinkRecordUpload: "drink_record_upload",
  errorCode: "error_code",
  childLock: "child_lock",
} as const;

export type DpCode = (typeof dpCodes)[keyof typeof dpCodes];
