export default {
  switch: "switch",
  startMilk: "milk",
  startWater: "water",
  startClean: "clean",
  startPowder: "powder",
  workMode: "work_mode",
  workingStatus: "working_status",
  tempSet: "temp",
  volumeMl: "ml",
  volumeOz: "oz",
  unitSet: "unit_set",
  formulaRatio: "formula_ratio",
  powderDensity: "powder_density",
  startBlockReason: "start_block_reason",
  sceneFeedRequest: "scene_feed_request",
  remindFunnelClean: "remind_funnel_clean",
  remindDailyPowderClean: "remind_daily_powder_clean",
  remindTankClean: "remind_tank_clean",
  wifiStatus: "wifi_status",
  drinkRecordUpload: "drink_record_upload",
  cancelWork: "cancel_work",
  errorCode: "error_code",
} as const;

export type DpCode = (typeof dpCodes)[keyof typeof dpCodes];
